### ISSUE TITLE
Inspect Nginx configuration (if used):

### ISSUE THREAD

**Issue by PESolut** [PESolut/my-resume#62]
This sub-ticket focuses on inspecting the Nginx configuration to troubleshoot the "Connection Refused" error encountered when accessing the deployed site through the custom domain. The Docker setup is confirmed to be functioning since the site renders correctly using the AWS Elastic IP. However, there could be a misconfiguration in Nginx contributing to the issue.

## Tasks:
- [ ] Verify nginx config files
- [ ]  check nginx logs
- [ ] confirm port and firewall rules
- [ ] check sll certifcate

## Acceptance Criteria:
- The Nginx configuration file contains the correct server block for the custom domain.
- Nginx passes the syntax check (nginx -t) without errors.
- There are no critical issues in the error logs.
- Nginx is properly serving the site via the custom domain without connection errors.
- If HTTPS is enabled, the SSL certificate is valid, and the site is accessible over both HTTP and HTTPS.

**Comment by PESolut** [comment]
task verify nginx config files..

## confirmation of no nginx syntax errors
[ec2-user@ip-172-31-27-183 ~]$ sudo nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

lets look at the nginx configs itself...

**Comment by PESolut** [comment]
# contents of nginx configs...

/etc/nginx/nginx.confg contents:
```
# For more information on configuration, see:
#   * Official English Documentation: http://nginx.org/en/docs/
#   * Official Russian Documentation: http://nginx.org/ru/docs/

user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log notice;
pid /run/nginx.pid;

# Load dynamic modules. See /usr/share/doc/nginx/README.dynamic.
include /usr/share/nginx/modules/*.conf;

events {
    worker_connections 1024;
}

http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile            on;
    tcp_nopush          on;
    keepalive_timeout   65;
    types_hash_max_size 4096;

    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;

    # Load modular configuration files from the /etc/nginx/conf.d directory.
    # See http://nginx.org/en/docs/ngx_core_module.html#include
    # for more information.
    include /etc/nginx/conf.d/*.conf;
# Settings for a TLS enabled server.
#
#    server {
#        listen       443 ssl http2;
#        listen       [::]:443 ssl http2;
#        server_name  _;
#        root         /usr/share/nginx/html;
#
#        ssl_certificate "/etc/pki/nginx/server.crt";
#        ssl_certificate_key "/etc/pki/nginx/private/server.key";
#        ssl_session_cache shared:SSL:1m;
#        ssl_session_timeout  10m;
#        ssl_ciphers PROFILE=SYSTEM;
#        ssl_prefer_server_ciphers on;
#
#
#        # Load configuration files for the default server block.
#        include /etc/nginx/default.d/*.conf;
#
#        error_page 404 /404.html;
#        location = /404.html {
#        }
#
#        error_page 500 502 503 504 /50x.html;
#        location = /50x.html {
#        }
#    }

}


```

**Comment by PESolut** [comment]
# contents of modular config file ( /etc/nginx/conf.d/jp-tech.conf )

```
   server {
       listen 80;
       server_name jp-tech.dev www.jp-tech.dev;

       location / {
           proxy_pass http://localhost:3000;
           proxy_http_version 1.1;
           proxy_set_header Upgrade $http_upgrade;
           proxy_set_header Connection 'upgrade';
           proxy_set_header Host $host;
           proxy_cache_bypass $http_upgrade;
       }
   }




``

**Comment by PESolut** [comment]
my init. thought is to confirm that  the jp-tech modular config file is being loaded properly.

**Comment by PESolut** [comment]
Attempting to look at log fiels and i have ownership issues it seems.. running these commands to switch

# Change ownership of the Nginx log directory
sudo chown -R nginx:nginx /var/log/nginx

# Set appropriate permissions
sudo chmod -R 755 /var/log/nginx

# Restart Nginx to ensure it picks up any changes
sudo systemctl restart nginx

# Check the Nginx status again
sudo systemctl status nginx

# Now try to list the contents of the log directory
sudo ls -l /var/log/nginx

**Comment by PESolut** [comment]
I can curl within the instance the localhost at port 3000 and also with no port supplied so port 80 so nginx is correctly proxying request to my application runing on port 3000
